export const FETCH_DESIGN_TYPES_START = "FETCH_DESIGN_TYPES_START";
export const FETCH_DESIGN_TYPES_SUCCESS = "FETCH_DESIGN_TYPES_SUCCESS";
export const FETCH_DESIGN_TYPES_FAILURE = "FETCH_DESIGN_TYPES_FAILURE";