export const FETCH_MANUFACTURERS_START = "FETCH_MANUFACTURERS_START";
export const FETCH_MANUFACTURERS_SUCCESS = "FETCH_MANUFACTURERS_SUCCESS";
export const FETCH_MANUFACTURERS_FAILURE = "FETCH_MANUFACTURERS_FAILURE";