export const SHOW_FEATURED = "SHOW_FEATURED";
export const SELECT_DESIGNER = "SELECT_DESIGNER";
export const FETCH_DESIGNS_START = "FETCH_DESIGNS_START";
export const FETCH_DESIGNS_SUCCESS = "FETCH_DESIGNS_SUCCESS";
export const FETCH_DESIGNS_FAILURE = "FETCH_DESIGNS_FAILURE";