export const FETCH_DESIGN_START = "FETCH_DESIGN_START";
export const FETCH_DESIGN_SUCCESS = "FETCH_DESIGN_SUCCESS";
export const FETCH_DESIGN_FAILURE = "FETCH_DESIGN_FAILURE";
export const RESET = "RESET";
