export const SHOW_FEATURED = "SHOW_FEATURED";
export const FETCH_DESIGNS_SUCCESS = "FETCH_DESIGNS_SUCCESS";
export const FETCH_DESIGNERS_SUCCESS = "FETCH_DESIGNERS_SUCCESS";
export const SELECT_DESIGNER = "SELECT_DESIGNER";