export const FETCH_MANUFACTURER_START = "FETCH_MANUFACTURER_START";
export const FETCH_MANUFACTURER_SUCCESS = "FETCH_MANUFACTURER_SUCCESS";
export const FETCH_MANUFACTURER_FAILURE = "FETCH_MANUFACTURER_FAILURE";
export const UPDATE_MANUFACTURER_START = "UPDATE_MANUFACTURER_START";
export const UPDATE_MANUFACTURER_SUCCESS = "UPDATE_MANUFACTURER_SUCCESS";
export const UPDATE_MANUFACTURER_FAILURE = "UPDATE_MANUFACTURER_FAILURE";