export const FETCH_MANUFACTURER_START = "FETCH_MANUFACTURER_START";
export const FETCH_MANUFACTURER_SUCCESS = "FETCH_MANUFACTURER_SUCCESS";
export const FETCH_MANUFACTURER_FAILURE = "FETCH_MANUFACTURER_FAILURE";